[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
bson = "2.13.0"
mongodb = "3.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
